Now also can clone a remote (https, ssh) repository into a new ZFS dataset

diff --git a/git-zclone b/git-zclone
--- a/git-zclone
+++ b/git-zclone
@@ -1,6 +1,7 @@
 #!/bin/bash
 
 ### Automate cloning of local Git repository stored as a dedicated ZFS dataset.
+### Also can clone a remote (https, ssh) repository into a new ZFS dataset.
 ### This supports creation of the clone mounted into a specified absolute path
 ### or into a relative path near the original repo. The user must have proper
 ### "zfs allow" delegated permissions for source and target datasets, list of
@@ -17,7 +18,7 @@
 ### local filesystem source and destination.
 ### Note that ZFS-based repository cloning also refers the non-repo cruft in
 ### the workspace, such as build products if in-tree builds were executed here.
-### Copyright (C) 2015 by Jim Klimov, License: MIT
+### Copyright (C) 2013-2015 by Jim Klimov, License: MIT
 
 PATH=/usr/gnu/bin:/usr/sfw/bin:/opt/sfw/bin:/opt/omniti/bin:/bin:\
 /sbin:/usr/sbin:$PATH
@@ -44,45 +45,63 @@ BAD=no
 if [ -e "$DEST" ]; then
 	BAD=yes
 	[ -d "$DEST" ] && \
-		( cd "$DEST" && [ x"`find . 2>/dev/null`" = x. ] ) && \
+		( cd "$DEST" && [ x"`find . 2>/dev/null | grep -v ./.zfs`" = x. ] ) && \
 		BAD=no
 fi
 [ x"$BAD" = xyes ] && \
 	echo "Required: DEST must not exist as a non-empty directory" >&2 && \
 	exit 1
 
-# Other sanity checks
-[ -z "$FROM" -o ! -d "$FROM" ] && \
-	echo "Required: FROM must exist as a directory" >&2 && exit 1
-FROMPATH="`cd "$FROM" && pwd`" || FROMPATH=""
-[ -z "$FROMPATH" ] && \
-	echo "Required: FROM must exist as a directory" >&2 && exit 1
-[ ! -d "$FROM/.git" ] && \
-	echo "Required: FROM must be a Git repository" >&2 && exit 1
-[ ! -d "$FROM/.zfs/snapshot" ] && \
-	echo "Required: FROM must be a ZFS POSIX dataset" >&2 && exit 1
+case "$FROM" in
+	*://*|*@*:*)
+		# TODO: This misses the "alternative scp-like syntax"
+		# aka   [user@]host.xz:path/to/repo.git/
+		echo "INFO: Detected the FROM repository as a remote URL"
+		FROM_TYPE=URL
+		# No local sanity checks at this moment
+		;;
+	*)
+		FROM_TYPE=LOCAL
+	# Other sanity checks
+	[ -z "$FROM" -o ! -d "$FROM" ] && \
+		echo "Required: FROM must exist as a directory" >&2 && exit 1
+	FROMPATH="`cd "$FROM" && pwd`" || FROMPATH=""
+	[ -z "$FROMPATH" ] && \
+		echo "Required: FROM must exist as a directory" >&2 && exit 1
+	[ ! -d "$FROM/.git" ] && \
+		echo "Required: FROM must be a Git repository" >&2 && exit 1
+	[ ! -d "$FROM/.zfs/snapshot" ] && \
+		echo "Required: FROM must be a ZFS POSIX dataset" >&2 && exit 1
 
-FROMDS="`cd "$FROMPATH" && df -k . | grep / | head -1 | awk '{print $1}'`" || \
-	FROMDS=""
-[ -z "$FROMDS" ] && \
-	echo "Required: FROM must be a mounted ZFS POSIX dataset" >&2 && exit 1
+	FROMDS="`cd "$FROMPATH" && df -k . | grep / | head -1 | awk '{print $1}'`" || \
+		FROMDS=""
+	[ -z "$FROMDS" ] && \
+		echo "Required: FROM must be a mounted ZFS POSIX dataset" >&2 && \
+		exit 1
+
+	# Validate both ZFS command and FROM dataset name
+	echo "=== FROM dataset:"
+	zfs list -o \
+		mountpoint,space,refer,lrefer,dedup,compression,compressratio,sharenfs,sharesmb \
+		"$FROMDS"
+	[ $? != 0 ] && \
+		echo "FATAL: Couldn't use ZFS to review dataset properties" >&2 && \
+		exit 1
+	;;
+esac
 
 # TODO: Maybe fallback to some other timestamp if this fails?
 # Perhaps a current latest git commit of the original repo?
-# Either way, some tag is needed to create the snapshot and then the clone.
-TS="`date -u '+%Y%m%dT%H%M%SZ'`" || TS=""
-[ -z "$TS" ] && \
-	echo "FATAL: Can't determine current timestamp" >&2 && exit 1
+# Either way, some tag is needed to create the (LOCAL) snapshot
+# and then the clone.
+TS="initialClone"
+if [ x"$FROM_TYPE" = xLOCAL ]; then
+	TS="`date -u '+%Y%m%dT%H%M%SZ'`" || TS=""
+	[ -z "$TS" ] && \
+		echo "FATAL: Can't determine current timestamp" >&2 && exit 1
+fi
 
-# Validate both ZFS command and FROM dataset name
-echo "=== FROM dataset:"
-zfs list -o \
-	mountpoint,space,refer,lrefer,dedup,compression,compressratio,sharenfs,sharesmb \
-	"$FROMDS"
-[ $? != 0 ] && \
-	echo "FATAL: Couldn't use ZFS to review dataset properties" >&2 && \
-	exit 1
-
+# Prerequisites seem good, begin non-readonly activity...
 [ -d "$DEST" ] || mkdir -p "$DEST"
 [ $? != 0 ] && \
 	echo "FATAL: Couldn't create the paths up to DEST" >&2 && exit 1
@@ -90,14 +109,17 @@ DESTPATH="`cd "$DEST" && pwd`" || DESTPATH=""
 [ -z "$DESTPATH" ] && \
 	echo "FATAL: Couldn't change the path into DEST" >&2 && exit 1
 
+# Determine the dataset that will hold the new repo and its mountpoint
 DESTDS=""
 DESTMPT=""
 if [ -d "$DESTPATH/.zfs/snapshot" ]; then
+	# This seems like a dataset already? Would be fatal later on for LOCAL.
 	DESTDS="`cd "$DESTPATH" && df -k . | grep / | head -1 | awk '{print $1}'`" || \
 	DESTDS=""
 fi
 
 if [ -z "$DESTDS" -a -d "$DESTPATH/../.zfs/snapshot" ]; then
+	# The (future) direct parent of DEST is a dataset?
 	DESTDS="`cd "$DESTPATH/.." && df -k . | grep / | head -1 | awk '{print $1}'`"/"`basename "$DESTPATH"`" || \
 	DESTDS=""
 
@@ -106,40 +128,92 @@ if [ -z "$DESTDS" -a -d "$DESTPATH/../.zfs/snapshot" ]; then
 fi
 
 if [ -z "$DESTDS" ]; then
-	DESTDS="`dirname "$FROMDS"`/`basename "$DESTPATH"`"
-	[ x"`dirname "$FROMPATH"`/`basename "$DEST"`" != x"$DESTPATH" ] && \
+	case "$FROM_TYPE" in
+	LOCAL)
+	    # Finally, try to spawn the clone "near" the original repo
+	    # Note that if it is mounted in an explicit location
+	    DESTDS="`dirname "$FROMDS"`/`basename "$DESTPATH"`"
+	    [ x"`dirname "$FROMPATH"`/`basename "$DEST"`" != x"$DESTPATH" ] && \
 		DESTMPT="$DESTPATH"
+	    ;;
+	URL)
+	    # Finally, try to spawn the clone under current directory's dataset
+	    DESTDS="`df -k . | grep / | head -1 | awk '{print $1}'`/`basename "$DESTPATH"`" || \
+	    DESTDS=""
+	    [ x"`pwd`/`basename "$DEST"`" != x"$DESTPATH" ] && \
+		DESTMPT="$DESTPATH"
+	    case "$DESTDS" in
+		/*|*:*|swap|"")	# Local non-ZFS path or an NFS mount
+		    echo "FATAL: The container backing store DESTDS='$DESTDS' does not seem like a local ZFS dataset!" >&2
+		    echo "Try:   git clone '$1' '$2'" >&2
+		    exit 1
+		    ;;
+	    esac
+	    ;;
+	esac
 fi
 
-# Validate both ZFS command and DEST dataset name
-zfs list -o name "$DESTDS" >/dev/null 2>&1 && \
-echo "FATAL: DEST ZFS dataset $DESTDS already exists?" >&2 && exit 2
+case "$FROM_TYPE" in
+    LOCAL)
+	# Validate both ZFS command and DEST dataset name
+	zfs list -o name "$DESTDS" >/dev/null 2>&1 && \
+		echo "FATAL: DEST ZFS dataset $DESTDS already exists?" \
+		    "Can't clone into it!" >&2 && exit 2
 
-echo "=== Cloning from '$FROMDS@git-auto-snap-clone-$TS'" \
-	"to '$DESTDS' (mountpoint=$DESTMPT)..."
+	echo "=== Cloning from '$FROMDS@git-auto-snap-clone-$TS'" \
+	    "to '$DESTDS' (mountpoint=$DESTMPT)..."
 
-zfs snapshot -r "$FROMDS@git-auto-snap-clone-$TS" || \
-{ RES=$?; echo "FATAL: Could not snapshot the dataset" \
-	"'$FROMDS@git-auto-snap-clone-$TS'" >&2; exit $RES; }
+	zfs snapshot -r "$FROMDS@git-auto-snap-clone-$TS" || \
+	{ RES=$?; echo "FATAL: Could not snapshot the dataset" \
+		"'$FROMDS@git-auto-snap-clone-$TS'" >&2; exit $RES; }
 
-zfs clone -p -o mountpoint=none \
-	"$FROMDS@git-auto-snap-clone-$TS" "$DESTDS" || \
-{ RES=$?
-  echo "FATAL: Could not clone the dataset"
-  echo "  from '$FROMDS@git-auto-snap-clone-$TS'"
-  echo "  to '$DESTDS'"
-  echo "Please make sure that dataset name is valid and that proper 'zfs allow'"
-  echo "permissions were set on destination container dataset, e.g. at least:"
-  echo "  sudo zfs allow -ldu $USER clone,create,destroy,diff,mount,promote,rollback,snapshot,share,sharenfs,sharesmb,canmount,mountpoint `dirname $DESTDS`"
-  echo "Maybe also allow: send,receive,dedup,compression,hold,release ..."
-  echo "::: Current set of destination container permissions is:"
-  zfs allow "`dirname $DESTDS`"
-  echo ""
-  echo "::: Current set of original repository dataset permissions is:"
-  zfs allow "$FROMDS"
-  echo ""
-  echo "FATAL: Dataset cloning FAILED"
-  exit $RES; } >&2
+	zfs clone -p -o mountpoint=none \
+		"$FROMDS@git-auto-snap-clone-$TS" "$DESTDS" || \
+	{ RES=$?
+	  echo "FATAL: Could not clone the dataset"
+	  echo "  from '$FROMDS@git-auto-snap-clone-$TS'"
+	  echo "  to '$DESTDS'"
+	  echo "Please make sure that dataset name is valid and that proper 'zfs allow'"
+	  echo "permissions were set on destination container dataset, e.g. at least:"
+	  echo "  sudo zfs allow -ldu $USER clone,create,destroy,diff,mount,promote,rollback,snapshot,share,sharenfs,sharesmb,canmount,mountpoint `dirname $DESTDS`"
+	  echo "Maybe also allow: send,receive,dedup,compression,hold,release ..."
+	  echo "::: Current set of destination container permissions is:"
+	  zfs allow "`dirname $DESTDS`"
+	  echo ""
+	  echo "::: Current set of original repository dataset permissions is:"
+	  zfs allow "$FROMDS"
+	  echo ""
+	  echo "FATAL: Dataset cloning FAILED"
+	  exit $RES; } >&2
+
+	echo "=== Trying to carry over some properties of the source dataset..."
+	EXCLUDE_ATTRS='canmount|mountpoint'
+	zfs get all "$FROMDS" | egrep ' (local|received)$' | \
+		egrep -v "$EXCLUDE_ATTRS" | while read _D A V _T; do \
+			echo "$A=$V"; zfs set "$A=$V" "$DESTDS"; \
+		done
+	# TODO: zfs allow permissions if set directly on FROMDS?
+	# TODO: zfs smb share ACL files?
+	# TODO: sub-datasets?
+	;;
+    URL)
+	if zfs list -o name "$DESTDS" >/dev/null 2>&1 ; then
+	    echo "NOTE: DEST ZFS dataset $DESTDS already exists (and is empty)"
+	else
+	    zfs create "$DESTDS" || \
+	{ RES=$?
+	  echo "FATAL: Could not create the dataset '$DESTDS'"
+	  echo "Please make sure that dataset name is valid and that proper 'zfs allow'"
+	  echo "permissions were set on destination container dataset, e.g. at least:"
+	  echo "  sudo zfs allow -ldu $USER clone,create,destroy,diff,mount,promote,rollback,snapshot,share,sharenfs,sharesmb,canmount,mountpoint `dirname $DESTDS`"
+	  exit $RES; } >&2
+	fi
+	;;
+    *)
+	echo "FATAL: Unimplemented FROM_TYPE='$FROM_TYPE'!" >&2
+	exit 3
+	;;
+esac
 
 RES=0
 if [ -n "$DESTMPT" ]; then
@@ -151,16 +225,6 @@ fi
 	echo "FATAL: Could not set '$DESTDS' mountpoint='$DESTMPT'" >&2 && \
 	exit $RES
 
-echo "=== Trying to carry over some properties of the source dataset..."
-EXCLUDE_ATTRS='canmount|mountpoint'
-zfs get all "$FROMDS" | egrep ' (local|received)$' | \
-	egrep -v "$EXCLUDE_ATTRS" | while read _D A V _T; do \
-		echo "$A=$V"; zfs set "$A=$V" "$DESTDS"; \
-	done
-# TODO: zfs allow permissions if set directly on FROMDS?
-# TODO: zfs smb share ACL files?
-# TODO: sub-datasets?
-
 echo "=== DEST dataset stats:"
 zfs list -o \
 	mountpoint,space,refer,lrefer,dedup,compression,compressratio,sharenfs,sharesmb \
@@ -171,24 +235,36 @@ zfs list -o \
 
 echo ""
 echo "=== Review ZFS ALLOW settings:"
-echo "===== FROM $FROMDS:"
-zfs allow "$FROMDS"
-echo ""
+if [ "$FROM_TYPE" = LOCAL ]; then
+	echo "===== FROM $FROMDS:"
+	zfs allow "$FROMDS"
+	echo ""
+fi
 echo "===== DEST $DESTDS:"
 zfs allow "$DESTDS"
 
-echo ""
-echo "=== Rewriting Git 'origin' of the new repo for automated sync with the parent"
-echo "    (in local filesystem); retaining the original 'origin' as 'origin-parent'"
-ORIGIN="$FROMPATH"
-[ x"`dirname "$FROMPATH"`" = x"`dirname "$DESTPATH"`" ] && \
-	ORIGIN="../`basename "$FROMPATH"`"
-( cd "$DESTPATH" && {
-  git remote rm origin-parent || echo "OK_TO_FAIL"
-  git remote rename origin origin-parent || echo "OK_TO_FAIL"
-  git remote add origin "$ORIGIN"; } ) || \
-{ RES=$?; echo "FATAL: Could not set Git origin URL"; exit $RES; } >&2
-### This was fatal because maybe "git" or "cd" failed, or something?
+case "$FROM_TYPE" in
+    LOCAL)
+	echo ""
+	echo "=== Rewriting Git 'origin' of the new repo for automated sync with the parent"
+	echo "    (in local filesystem); retaining the original 'origin' as 'origin-parent'"
+	ORIGIN="$FROMPATH"
+	[ x"`dirname "$FROMPATH"`" = x"`dirname "$DESTPATH"`" ] && \
+		ORIGIN="../`basename "$FROMPATH"`"
+	( cd "$DESTPATH" && {
+	  git remote rm origin-parent || echo "OK_TO_FAIL"
+	  git remote rename origin origin-parent || echo "OK_TO_FAIL"
+	  git remote add origin "$ORIGIN"; } ) || \
+	{ RES=$?; echo "FATAL: Could not set Git origin URL"; exit $RES; } >&2
+	### This was fatal because maybe "git" or "cd" failed, or something?
+	;;
+    URL)
+	cd "$DESTPATH" && git clone "$1" . || \
+	{ RES=$?
+	  echo "FATAL: Could not clone remote Git repo '$1' to local dataset '$DESTDS' mounted at '$DESTPATH'"
+	  exit $RES; } >&2
+	;;
+esac
 
 echo ""
 echo "=== Rewriting Git branch tracking for the current branch of the new repo"
@@ -213,7 +289,8 @@ fi
 
 echo ""
 echo "=== SUCCESS: git zclone '$FROM' '$DEST':" \
-	"created '$DESTDS' mounted to '$DESTPATH'" \
+	"created '$DESTDS' mounted to '$DESTPATH'"
+[ "$FROM_TYPE" = LOCAL ] && \
 	"and changed git origin to '$ORIGIN'"
 if [ "$RES" != 0 ]; then
 	echo "=== WARN: Some non-fatal failures were detected" \
